Added testimonials
OronNadiv/myfirststepsdaycare.com pull request #1
Opened 2019-09-08 21:16 UTC by myfirststepsdaycare

- Reordered in chronological order
- Anonymized names
- Added additional testimonials

2019-09-13 03:39 UTC, OronNadiv requested changes

2019-09-13 03:39 UTC, OronNadiv commented on src/routes/Testimonials/state.js
> +          [<a onClick={cb}>Read Full Testimonial</a>]
@myfirststepsdaycare - not sure why you switched from `<Link>` to `<a>`.  `Link` is a react-router object that should be used for routing.
Either way, adding an `a` tag without `href` would result in lint errors.
Also, at the top of the page, you still have `import { Link } from 'react-router-dom'`.  If you don't use it (which you don't), it would result with another lint error.
I would suggest bringing back the `Link` tag.  Other than that, everything else looks good.

2019-09-15 22:56 UTC, myfirststepsdaycare commented on src/routes/Testimonials/state.js
> +          [<a onClick={cb}>Read Full Testimonial</a>]
Sorry, that was an oversight (had branched from an earlier commit and didn't see the React changes). I added the <Link>'s back

2019-09-19 05:34 UTC, OronNadiv approved these changes

2019-09-19 05:34 UTC, merged